import Link from 'next/link';
import { SITE_URL } from '@/lib/constants/site';

interface PostFooterBadgeProps {
  locale?: string;
}

const BADGE_TEXT: Record<string, string> = {
  ko: '이 포스트는 Synapso로 자동 생성되었습니다.',
  en: 'This post was auto-generated by Synapso.',
};

export function PostFooterBadge({ locale = 'ko' }: PostFooterBadgeProps) {
  const text = BADGE_TEXT[locale] ?? BADGE_TEXT['ko'];
  return (
    <div className="mt-8 pt-6 border-t border-neutral-200 dark:border-neutral-800">
      <p className="text-sm text-neutral-500 dark:text-neutral-400">
        {text}{' '}
        <Link
          href={SITE_URL}
          target="_blank"
          rel="noopener noreferrer"
          className="underline hover:text-neutral-700 dark:hover:text-neutral-200"
        >
          Synapso.dev
        </Link>
      </p>
    </div>
  );
}

export default PostFooterBadge;
