import Anthropic from "@anthropic-ai/sdk";
import { GenerateResult } from "./types";

const client = new Anthropic(); // reads ANTHROPIC_API_KEY

export interface PolishResult {
  content: string;
  summary: string; // SEO-optimized, ≤140 chars
  seoKeywords: string[];
}

export async function polishPost(draft: GenerateResult): Promise<PolishResult> {
  const response = await client.messages.create({
    model: "claude-sonnet-4-6",
    max_tokens: 8000,
    tools: [
      {
        name: "polished_post",
        description: "Output the polished blog post with SEO metadata",
        input_schema: {
          type: "object" as const,
          additionalProperties: false,
          required: ["content", "summary", "seoKeywords"],
          properties: {
            content: { type: "string" },
            summary: { type: "string" },
            seoKeywords: { type: "array", items: { type: "string" } },
          },
        },
      },
    ],
    tool_choice: { type: "tool", name: "polished_post" },
    system: `You are an expert Korean technical editor and SEO specialist.
You will receive a Korean-language technical blog post generated by AI from GitHub commit analysis.

Your task:
1. "content": Polish the Markdown blog post. Fix grammar/awkward phrasing, improve prose flow, ensure consistent professional tone. Keep all technical accuracy and code blocks unchanged. Do not shorten substantially.
2. "summary": Write a compelling Korean meta description ≤140 characters that includes the primary keywords and clearly states the value of the post.
3. "seoKeywords": Extract 5–8 additional Korean/English search terms NOT already in the post's existing tags. Focus on terms developers would search for.`,
    messages: [
      {
        role: "user",
        content: `제목: ${draft.title}

기존 요약: ${draft.summary}

기존 태그: ${draft.tags.join(", ")}

본문 (Markdown):
${draft.content}`,
      },
    ],
  });

  const toolUseBlock = response.content.find((b) => b.type === "tool_use");
  if (!toolUseBlock || toolUseBlock.type !== "tool_use") {
    throw new Error("Claude polishing pass가 tool_use 결과를 반환하지 않았습니다.");
  }

  return toolUseBlock.input as PolishResult;
}
