import { getDemoPosts } from "@/lib/demo";
import DemoPostCard from "@/components/demo/DemoPostCard";
import { getTranslations } from "next-intl/server";
import { PageContainer } from "@/components/ui/PageContainer";
import { Metadata } from "next";

export const revalidate = 3600; // 1시간마다 ISR 갱신

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}): Promise<Metadata> {
  const { locale } = await params;
  const isEn = locale === "en";
  
  return {
    title: isEn ? "AI Tech Blog Demo | Synapso.dev" : "AI 기술 블로그 데모 | Synapso.dev",
    description: isEn 
      ? "Explore actual tech blog posts generated by Gemini AI from GitHub commits."
      : "GitHub 커밋을 기반으로 Gemini AI가 생성한 실제 기술 블로그 포스트들을 확인해보세요.",
    openGraph: {
      title: isEn ? "AI Tech Blog Demo" : "AI 기술 블로그 데모",
      description: isEn 
        ? "Turn your code into content instantly."
        : "당신의 코드를 즉시 가치 있는 기술 콘텐츠로 변환하세요.",
    }
  };
}

export default async function MarketingDemoPage({
  params,
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  const t = await getTranslations("MarketingDemo");
  const posts = await getDemoPosts();

  return (
    <PageContainer>
      <div className="max-w-6xl mx-auto py-12 px-4">
        <div className="text-center mb-16 animate-fade-in">
          <h1 className="text-4xl md:text-5xl font-extrabold mb-6 bg-gradient-to-r from-accent to-accent-strong bg-clip-text text-transparent">
            {t("title")}
          </h1>
          <p className="text-lg text-text-secondary max-w-2xl mx-auto">
            {t("desc")}
          </p>
        </div>

        {posts.length > 0 ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {posts.map((post, index) => (
              <DemoPostCard key={post.id} post={post} index={index} />
            ))}
          </div>
        ) : (
          <div className="text-center py-24 border border-dashed border-border-subtle rounded-3xl">
            <p className="text-text-tertiary">{t("empty")}</p>
          </div>
        )}
      </div>
    </PageContainer>
  );
}
